export type InvoiceMode = "gst" | "non-gst" | "quotation";
export type InvoiceItem = { product: string; hsn: string; qty: number; rate: number; gstPercent: number };
export type InvoiceDraft = { mode: InvoiceMode; invoice: string; customerId: string; date: string; validUntil: string; customer: string; customerPhone: string; customerAddress: string; customerCity: string; customerState: string; gstin: string; items: InvoiceItem[]; discount: number; paid: number; paymentMode: string; notes: string };
export const COMPANY = { name: "OBOSCO CLOTHING INDUSTRIES", address: "Near by Police Station Tanur, First Floor 22/242", state: "Kerala", phone: "+91 8089457918" };
export const emptyItem = (): InvoiceItem => ({ product: "", hsn: "", qty: 1, rate: 0, gstPercent: 0 });
export function itemValues(item: InvoiceItem, mode: InvoiceMode) { const taxable = Math.max(0, (item.qty || 0) * (item.rate || 0)); const gst = mode === "gst" ? +(taxable * ((item.gstPercent || 0) / 100)).toFixed(2) : 0; return { taxable, gst, total: +(taxable + gst).toFixed(2) }; }
export function invoiceTotals(draft: Pick<InvoiceDraft, "mode" | "items" | "discount" | "paid">) { const taxable = draft.items.reduce((sum, item) => sum + itemValues(item, draft.mode).taxable, 0); const gst = draft.items.reduce((sum, item) => sum + itemValues(item, draft.mode).gst, 0); const subtotal = Math.max(0, taxable - (draft.discount || 0)); const total = +(subtotal + gst).toFixed(2); const paid = Math.min(Math.max(0, draft.paid || 0), total); return { taxable: +taxable.toFixed(2), subtotal: +subtotal.toFixed(2), gst: +gst.toFixed(2), total, paid, due: +(total - paid).toFixed(2) }; }
const ones = ["Zero", "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine", "Ten", "Eleven", "Twelve", "Thirteen", "Fourteen", "Fifteen", "Sixteen", "Seventeen", "Eighteen", "Nineteen"];
const tens = ["", "", "Twenty", "Thirty", "Forty", "Fifty", "Sixty", "Seventy", "Eighty", "Ninety"];
function underThousand(value: number): string { if (value < 20) return ones[value]; if (value < 100) return `${tens[Math.floor(value / 10)]}${value % 10 ? ` ${ones[value % 10]}` : ""}`; return `${ones[Math.floor(value / 100)]} Hundred${value % 100 ? ` ${underThousand(value % 100)}` : ""}`; }
export function amountInWords(amount: number) { let value = Math.max(0, Math.round(amount)); if (!value) return "Rupees Zero Only"; const parts: string[] = []; if (value >= 10000000) { parts.push(`${underThousand(Math.floor(value / 10000000))} Crore`); value %= 10000000; } if (value >= 100000) { parts.push(`${underThousand(Math.floor(value / 100000))} Lakh`); value %= 100000; } if (value >= 1000) { parts.push(`${underThousand(Math.floor(value / 1000))} Thousand`); value %= 1000; } if (value) parts.push(underThousand(value)); return `Rupees ${parts.join(" ")} Only`; }
export function modeLabel(mode: InvoiceMode) { return mode === "gst" ? "TAX INVOICE (B2C)" : mode === "non-gst" ? "BILL" : "QUOTATION"; }
