/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedDownloadsRouteImport } from './routes/_authenticated/downloads'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedInvoicesIndexRouteImport } from './routes/_authenticated/invoices.index'
import { Route as AuthenticatedSheetSlugRouteImport } from './routes/_authenticated/sheet.$slug'
import { Route as AuthenticatedInvoicesNewRouteImport } from './routes/_authenticated/invoices.new'
import { Route as AuthenticatedInvoicesInvoiceRouteImport } from './routes/_authenticated/invoices.$invoice'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDownloadsRoute = AuthenticatedDownloadsRouteImport.update({
  id: '/_authenticated/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/_authenticated/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedInvoicesIndexRoute =
  AuthenticatedInvoicesIndexRouteImport.update({
    id: '/_authenticated/invoices/',
    path: '/invoices/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSheetSlugRoute = AuthenticatedSheetSlugRouteImport.update({
  id: '/_authenticated/sheet/$slug',
  path: '/sheet/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedInvoicesNewRoute =
  AuthenticatedInvoicesNewRouteImport.update({
    id: '/_authenticated/invoices/new',
    path: '/invoices/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedInvoicesInvoiceRoute =
  AuthenticatedInvoicesInvoiceRouteImport.update({
    id: '/_authenticated/invoices/$invoice',
    path: '/invoices/$invoice',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/downloads': typeof AuthenticatedDownloadsRoute
  '/': typeof AuthenticatedIndexRoute
  '/invoices/$invoice': typeof AuthenticatedInvoicesInvoiceRoute
  '/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/sheet/$slug': typeof AuthenticatedSheetSlugRoute
  '/invoices/': typeof AuthenticatedInvoicesIndexRoute
}
export interface FileRoutesByTo {
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/downloads': typeof AuthenticatedDownloadsRoute
  '/': typeof AuthenticatedIndexRoute
  '/invoices/$invoice': typeof AuthenticatedInvoicesInvoiceRoute
  '/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/sheet/$slug': typeof AuthenticatedSheetSlugRoute
  '/invoices': typeof AuthenticatedInvoicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/downloads': typeof AuthenticatedDownloadsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/invoices/$invoice': typeof AuthenticatedInvoicesInvoiceRoute
  '/_authenticated/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/_authenticated/sheet/$slug': typeof AuthenticatedSheetSlugRoute
  '/_authenticated/invoices/': typeof AuthenticatedInvoicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/analytics'
    | '/downloads'
    | '/'
    | '/invoices/$invoice'
    | '/invoices/new'
    | '/sheet/$slug'
    | '/invoices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/analytics'
    | '/downloads'
    | '/'
    | '/invoices/$invoice'
    | '/invoices/new'
    | '/sheet/$slug'
    | '/invoices'
  id:
    | '__root__'
    | '/_authenticated/analytics'
    | '/_authenticated/downloads'
    | '/_authenticated/'
    | '/_authenticated/invoices/$invoice'
    | '/_authenticated/invoices/new'
    | '/_authenticated/sheet/$slug'
    | '/_authenticated/invoices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedDownloadsRoute: typeof AuthenticatedDownloadsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedInvoicesInvoiceRoute: typeof AuthenticatedInvoicesInvoiceRoute
  AuthenticatedInvoicesNewRoute: typeof AuthenticatedInvoicesNewRoute
  AuthenticatedSheetSlugRoute: typeof AuthenticatedSheetSlugRoute
  AuthenticatedInvoicesIndexRoute: typeof AuthenticatedInvoicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/downloads': {
      id: '/_authenticated/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof AuthenticatedDownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/invoices/': {
      id: '/_authenticated/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AuthenticatedInvoicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sheet/$slug': {
      id: '/_authenticated/sheet/$slug'
      path: '/sheet/$slug'
      fullPath: '/sheet/$slug'
      preLoaderRoute: typeof AuthenticatedSheetSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/invoices/new': {
      id: '/_authenticated/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof AuthenticatedInvoicesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/invoices/$invoice': {
      id: '/_authenticated/invoices/$invoice'
      path: '/invoices/$invoice'
      fullPath: '/invoices/$invoice'
      preLoaderRoute: typeof AuthenticatedInvoicesInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedDownloadsRoute: AuthenticatedDownloadsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedInvoicesInvoiceRoute: AuthenticatedInvoicesInvoiceRoute,
  AuthenticatedInvoicesNewRoute: AuthenticatedInvoicesNewRoute,
  AuthenticatedSheetSlugRoute: AuthenticatedSheetSlugRoute,
  AuthenticatedInvoicesIndexRoute: AuthenticatedInvoicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
